apiVersion: v1
kind: Service
metadata:
  name: calificaciones-up-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: calificaciones-up-api
  ports:
    - name: http
      port: 8081
      targetPort: http

