apiVersion: v1
kind: Service
metadata:
  name: calificaciones-up-web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: calificaciones-up-web
  ports:
    - name: http
      port: 3000
      targetPort: http

