[phases.setup]
nixPkgs = ["bun", "nodejs_22"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["bun run build:web"]

[start]
cmd = "node apps/web/.next/standalone/apps/web/server.js"
